version: '2'

services:
  nginx:
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
      - frontend
    environment:
      VIRTUAL_HOST: algolia.docker
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
    container_name: praagya-algolia-nginx

  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: algolia
    container_name: praagya-algolia-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: algolia
    container_name: praagya-algolia-mongo-express

  backend:
    build: ./backend
    command: rails s -p 3000 -b '0.0.0.0'
    entrypoint: ./scripts/dockerEntrypoint.sh
    links:
      - frontend
      - mongo
    volumes:
      - ./backend:/app
    container_name: praagya-algolia-backend

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    container_name: praagya-algolia-frontend
