version: '2'

services:
  nginx:
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
      - frontend
    environment:
      VIRTUAL_HOST: algolia.docker
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
    container_name: praagya-algolia-nginx

  # TODO: add mongo db reference

  backend:
    build: ./backend
    command: rails s -p 3000 -b '0.0.0.0'
    entrypoint: ./scripts/dockerEntrypoint.sh
    links:
      - frontend
    volumes:
      - ./backend:/app
    depends_on:
      # - db
      - frontend
    container_name: praagya-algolia-backend

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    container_name: praagya-algolia-frontend
